"""add barcode to products

Revision ID: 945c0a9f7393
Revises: edcc7b7b533d
Create Date: 2026-07-10 10:01:34.681986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945c0a9f7393'
down_revision: Union[str, Sequence[str], None] = 'edcc7b7b533d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.create_unique_constraint("uq_products_barcode", 'products', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_barcode", 'products', type_='unique')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
