"""add product_category_id foreign key

Revision ID: 5e93fada63a7
Revises: 9d1e5f679fe3
Create Date: 2026-07-14 09:35:32.714319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e93fada63a7'
down_revision: Union[str, Sequence[str], None] = '9d1e5f679fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_products_category_id_categories', 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_category_id_categories', 'products', type_='foreignkey')
    # ### end Alembic commands ###
